### ISSUE TITLE
'cannot load such file -- clipboard (LoadError)'

### ISSUE THREAD

**Issue by amarmh** [patilsuraj767/ttoken#1]
~~~
# ttoken --encrypt
Traceback (most recent call last):
	7: from /usr/local/bin/ttoken:23:in `<main>'
	6: from /usr/local/bin/ttoken:23:in `load'
	5: from /usr/local/share/gems/gems/ttoken-0.1.0/bin/ttoken:5:in `<top (required)>'
	4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	2: from /usr/local/share/gems/gems/ttoken-0.1.0/lib/ttoken.rb:3:in `<top (required)>'
	1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- clipboard (LoadError)
~~~
~~~
# rpm -qa |egrep "ruby|rubygems|xclip"
rubygem-bigdecimal-2.0.0-132.fc32.x86_64
rubygem-json-2.3.0-201.fc32.x86_64
ruby-2.7.1-132.fc32.x86_64
xclip-0.13-9.fc32.x86_64    <<<<<
rubygem-bundler-2.1.4-132.fc32.noarch
rubypick-1.1.1-12.fc32.noarch
rubygem-openssl-2.1.2-132.fc32.x86_64
rubygem-irb-1.2.3-132.fc32.noarch
rubygem-asciidoctor-2.0.10-2.fc32.noarch
ruby-libs-2.7.1-132.fc32.x86_64
rubygem-rdoc-6.2.1-132.fc32.noarch
rubygem-psych-3.1.0-132.fc32.x86_64
rubygems-3.1.2-132.fc32.noarch
ruby-default-gems-2.7.1-132.fc32.noarch
rubygem-io-console-0.5.6-132.fc32.x86_64
~~~

**Comment by patilsuraj767** [comment]
@amarmh   Remove line `require 'clipboard'` - https://github.com/patilsuraj767/ttoken/blob/ac3268fe33bd454da6fab1021b0b32d2b4144295/lib/ttoken.rb#L3

OR 

`gem install clipboard`
